// Sample vocabulary data
const vocabularyData = [
{
    id: "water_001",
    english: "water",
    hiragana: "みず",
    katakana: "ミズ",
    kanji: "水",
    romaji: "mizu",
    commonWriting: "水",
    wordType: "noun",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "daily-life", "drinks", "essential"],
    relatedWords: ["drink", "tea"]
},
{
    id: "drink_001",
    english: "to drink",
    hiragana: "のむ",
    katakana: "ノム",
    kanji: "飲む",
    romaji: "nomu",
    commonWriting: "飲む",
    wordType: "godan-verb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "daily-life", "verbs", "essential"],
    relatedWords: ["water", "tea", "eat"]
},
{
    id: "big_001",
    english: "big",
    hiragana: "おおきい",
    katakana: "オオキイ",
    kanji: "大きい",
    romaji: "ookii",
    commonWriting: "大きい",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0011",
    tags: ["basic", "adjectives", "size"],
    relatedWords: ["small", "size"]
},
{
    id: "small_001",
    english: "small",
    hiragana: "ちいさい",
    katakana: "チイサイ",
    kanji: "小さい",
    romaji: "chiisai",
    commonWriting: "小さい",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0011",
    tags: ["basic", "adjectives", "size"],
    relatedWords: ["big", "size"]
},
{
    id: "eat_001",
    english: "to eat",
    hiragana: "たべる",
    katakana: "タベル",
    kanji: "食べる",
    romaji: "taberu",
    commonWriting: "食べる",
    wordType: "ichidan-verb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "daily-life", "verbs", "essential"],
    relatedWords: ["drink", "food", "rice"]
},
{
    id: "rice_001",
    english: "rice/meal",
    hiragana: "ごはん",
    katakana: "ゴハン",
    kanji: "御飯",
    romaji: "gohan",
    commonWriting: "ごはん",
    wordType: "noun",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "food", "daily-life", "essential"],
    relatedWords: ["eat", "food", "lunch"]
},
{
    id: "tea_001",
    english: "tea",
    hiragana: "おちゃ",
    katakana: "オチャ",
    kanji: "お茶",
    romaji: "ocha",
    commonWriting: "お茶",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "drinks", "daily-life"],
    relatedWords: ["drink", "water", "hot"]
},
{
    id: "hot_001",
    english: "hot",
    hiragana: "あつい",
    katakana: "アツイ",
    kanji: "熱い",
    romaji: "atsui",
    commonWriting: "熱い",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "adjectives", "temperature"],
    relatedWords: ["cold", "temperature", "tea"]
},
{
    id: "cold_001",
    english: "cold",
    hiragana: "さむい",
    katakana: "サムイ",
    kanji: "寒い",
    romaji: "samui",
    commonWriting: "寒い",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "adjectives", "temperature", "weather"],
    relatedWords: ["hot", "temperature", "winter"]
},
{
    id: "good_001",
    english: "good",
    hiragana: "いい",
    katakana: "イイ",
    kanji: "良い",
    romaji: "ii",
    commonWriting: "いい",
    wordType: "i-adjective",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "adjectives", "essential", "emotions"],
    relatedWords: ["bad", "nice", "okay"]
},
{
    id: "bad_001",
    english: "bad",
    hiragana: "わるい",
    katakana: "ワルイ",
    kanji: "悪い",
    romaji: "warui",
    commonWriting: "悪い",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "adjectives", "emotions"],
    relatedWords: ["good", "terrible"]
},
{
    id: "person_001",
    english: "person",
    hiragana: "ひと",
    katakana: "ヒト",
    kanji: "人",
    romaji: "hito",
    commonWriting: "人",
    wordType: "noun",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "people", "essential"],
    relatedWords: ["man", "woman", "people"]
},
{
    id: "man_001",
    english: "man",
    hiragana: "おとこ",
    katakana: "オトコ",
    kanji: "男",
    romaji: "otoko",
    commonWriting: "男",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "people", "gender"],
    relatedWords: ["woman", "person", "boy"]
},
{
    id: "woman_001",
    english: "woman",
    hiragana: "おんな",
    katakana: "オンナ",
    kanji: "女",
    romaji: "onna",
    commonWriting: "女",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "people", "gender"],
    relatedWords: ["man", "person", "girl"]
},
{
    id: "child_001",
    english: "child",
    hiragana: "こども",
    katakana: "コドモ",
    kanji: "子供",
    romaji: "kodomo",
    commonWriting: "子供",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "people", "family"],
    relatedWords: ["boy", "girl", "family"]
},
{
    id: "mother_001",
    english: "mother",
    hiragana: "おかあさん",
    katakana: "オカアサン",
    kanji: "お母さん",
    romaji: "okaasan",
    commonWriting: "お母さん",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["basic", "family", "people"],
    relatedWords: ["father", "parent", "family"]
},
{
    id: "father_001",
    english: "father",
    hiragana: "おとうさん",
    katakana: "オトウサン",
    kanji: "お父さん",
    romaji: "otousan",
    commonWriting: "お父さん",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["basic", "family", "people"],
    relatedWords: ["mother", "parent", "family"]
},
{
    id: "house_001",
    english: "house/home",
    hiragana: "いえ",
    katakana: "イエ",
    kanji: "家",
    romaji: "ie",
    commonWriting: "家",
    wordType: "noun",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "places", "daily-life", "essential"],
    relatedWords: ["home", "family", "room"]
},
{
    id: "school_001",
    english: "school",
    hiragana: "がっこう",
    katakana: "ガッコウ",
    kanji: "学校",
    romaji: "gakkou",
    commonWriting: "学校",
    wordType: "noun",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["basic", "places", "education", "essential"],
    relatedWords: ["student", "teacher", "study"]
},
{
    id: "student_001",
    english: "student",
    hiragana: "がくせい",
    katakana: "ガクセイ",
    kanji: "学生",
    romaji: "gakusei",
    commonWriting: "学生",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["basic", "people", "education"],
    relatedWords: ["school", "teacher", "study"]
},
{
    id: "teacher_001",
    english: "teacher",
    hiragana: "せんせい",
    katakana: "センセイ",
    kanji: "先生",
    romaji: "sensei",
    commonWriting: "先生",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["basic", "people", "education", "occupations"],
    relatedWords: ["student", "school", "teach"]
},
{
    id: "book_001",
    english: "book",
    hiragana: "ほん",
    katakana: "ホン",
    kanji: "本",
    romaji: "hon",
    commonWriting: "本",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "objects", "education", "reading"],
    relatedWords: ["read", "study", "magazine"]
},
{
    id: "read_001",
    english: "to read",
    hiragana: "よむ",
    katakana: "ヨム",
    kanji: "読む",
    romaji: "yomu",
    commonWriting: "読む",
    wordType: "godan-verb",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "verbs", "education", "daily-life"],
    relatedWords: ["book", "study", "write"]
},
{
    id: "write_001",
    english: "to write",
    hiragana: "かく",
    katakana: "カク",
    kanji: "書く",
    romaji: "kaku",
    commonWriting: "書く",
    wordType: "godan-verb",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "verbs", "education", "daily-life"],
    relatedWords: ["read", "letter", "pen"]
},
{
    id: "time_001",
    english: "time",
    hiragana: "じかん",
    katakana: "ジカン",
    kanji: "時間",
    romaji: "jikan",
    commonWriting: "時間",
    wordType: "noun",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "time", "essential"],
    relatedWords: ["hour", "minute", "clock"]
},
{
    id: "today_001",
    english: "today",
    hiragana: "きょう",
    katakana: "キョウ",
    kanji: "今日",
    romaji: "kyou",
    commonWriting: "今日",
    wordType: "noun",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "time", "essential", "daily-life"],
    relatedWords: ["yesterday", "tomorrow", "day"]
},
{
    id: "yesterday_001",
    english: "yesterday",
    hiragana: "きのう",
    katakana: "キノウ",
    kanji: "昨日",
    romaji: "kinou",
    commonWriting: "昨日",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "time", "daily-life"],
    relatedWords: ["today", "tomorrow", "day"]
},
{
    id: "tomorrow_001",
    english: "tomorrow",
    hiragana: "あした",
    katakana: "アシタ",
    kanji: "明日",
    romaji: "ashita",
    commonWriting: "明日",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "time", "daily-life"],
    relatedWords: ["today", "yesterday", "day"]
},
{
    id: "morning_001",
    english: "morning",
    hiragana: "あさ",
    katakana: "アサ",
    kanji: "朝",
    romaji: "asa",
    commonWriting: "朝",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "time", "daily-life"],
    relatedWords: ["evening", "night", "day"]
},
{
    id: "night_001",
    english: "night",
    hiragana: "よる",
    katakana: "ヨル",
    kanji: "夜",
    romaji: "yoru",
    commonWriting: "夜",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "time", "daily-life"],
    relatedWords: ["morning", "evening", "day"]
},
{
    id: "go_001",
    english: "to go",
    hiragana: "いく",
    katakana: "イク",
    kanji: "行く",
    romaji: "iku",
    commonWriting: "行く",
    wordType: "godan-verb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "verbs", "movement", "essential"],
    relatedWords: ["come", "return", "walk"]
},
{
    id: "come_001",
    english: "to come",
    hiragana: "くる",
    katakana: "クル",
    kanji: "来る",
    romaji: "kuru",
    commonWriting: "来る",
    wordType: "irregular-verb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "verbs", "movement", "essential"],
    relatedWords: ["go", "return", "arrive"]
},
{
    id: "return_001",
    english: "to return",
    hiragana: "かえる",
    katakana: "カエル",
    kanji: "帰る",
    romaji: "kaeru",
    commonWriting: "帰る",
    wordType: "godan-verb",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "verbs", "movement"],
    relatedWords: ["go", "come", "home"]
},
{
    id: "see_001",
    english: "to see/watch",
    hiragana: "みる",
    katakana: "ミル",
    kanji: "見る",
    romaji: "miru",
    commonWriting: "見る",
    wordType: "ichidan-verb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "verbs", "senses", "essential"],
    relatedWords: ["look", "watch", "movie"]
},
{
    id: "hear_001",
    english: "to hear/listen",
    hiragana: "きく",
    katakana: "キク",
    kanji: "聞く",
    romaji: "kiku",
    commonWriting: "聞く",
    wordType: "godan-verb",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "verbs", "senses"],
    relatedWords: ["listen", "music", "sound"]
},
{
    id: "speak_001",
    english: "to speak/talk",
    hiragana: "はなす",
    katakana: "ハナス",
    kanji: "話す",
    romaji: "hanasu",
    commonWriting: "話す",
    wordType: "godan-verb",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "verbs", "communication"],
    relatedWords: ["talk", "say", "language"]
},
{
    id: "money_001",
    english: "money",
    hiragana: "おかね",
    katakana: "オカネ",
    kanji: "お金",
    romaji: "okane",
    commonWriting: "お金",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "objects", "daily-life"],
    relatedWords: ["buy", "expensive", "cheap"]
},
{
    id: "buy_001",
    english: "to buy",
    hiragana: "かう",
    katakana: "カウ",
    kanji: "買う",
    romaji: "kau",
    commonWriting: "買う",
    wordType: "godan-verb",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "verbs", "shopping", "daily-life"],
    relatedWords: ["money", "shop", "sell"]
},
{
    id: "car_001",
    english: "car",
    hiragana: "くるま",
    katakana: "クルマ",
    kanji: "車",
    romaji: "kuruma",
    commonWriting: "車",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["basic", "transportation", "objects"],
    relatedWords: ["drive", "bus", "train"]
},
{
    id: "train_001",
    english: "train",
    hiragana: "でんしゃ",
    katakana: "デンシャ",
    kanji: "電車",
    romaji: "densha",
    commonWriting: "電車",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["basic", "transportation", "daily-life"],
    relatedWords: ["car", "bus", "station"]
},
{
    id: "station_001",
    english: "station",
    hiragana: "えき",
    katakana: "エキ",
    kanji: "駅",
    romaji: "eki",
    commonWriting: "駅",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["basic", "places", "transportation"],
    relatedWords: ["train", "bus", "platform"]
},
{
    id: "hospital_001",
    english: "hospital",
    hiragana: "びょういん",
    katakana: "ビョウイン",
    kanji: "病院",
    romaji: "byouin",
    commonWriting: "病院",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["basic", "places", "medical"],
    relatedWords: ["doctor", "sick", "medicine"]
},
{
    id: "restaurant_001",
    english: "restaurant",
    hiragana: "レストラン",
    katakana: "レストラン",
    kanji: "",
    romaji: "resutoran",
    commonWriting: "レストラン",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01111",
    tags: ["basic", "places", "food", "daily-life"],
    relatedWords: ["eat", "food", "dinner"]
},
{
    id: "friend_001",
    english: "friend",
    hiragana: "ともだち",
    katakana: "トモダチ",
    kanji: "友達",
    romaji: "tomodachi",
    commonWriting: "友達",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["basic", "people", "relationships"],
    relatedWords: ["person", "talk", "meet"]
},
{
    id: "dog_001",
    english: "dog",
    hiragana: "いぬ",
    katakana: "イヌ",
    kanji: "犬",
    romaji: "inu",
    commonWriting: "犬",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["animals", "pets", "basic"],
    relatedWords: ["cat", "animal", "pet"]
},
{
    id: "cat_001",
    english: "cat",
    hiragana: "ねこ",
    katakana: "ネコ",
    kanji: "猫",
    romaji: "neko",
    commonWriting: "猫",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["animals", "pets", "basic"],
    relatedWords: ["dog", "animal", "pet"]
},
{
    id: "fish_001",
    english: "fish",
    hiragana: "さかな",
    katakana: "サカナ",
    kanji: "魚",
    romaji: "sakana",
    commonWriting: "魚",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["animals", "food", "basic"],
    relatedWords: ["eat", "sea", "swim"]
},
{
    id: "bird_001",
    english: "bird",
    hiragana: "とり",
    katakana: "トリ",
    kanji: "鳥",
    romaji: "tori",
    commonWriting: "鳥",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["animals", "nature", "basic"],
    relatedWords: ["fly", "sky", "sing"]
},
{
    id: "flower_001",
    english: "flower",
    hiragana: "はな",
    katakana: "ハナ",
    kanji: "花",
    romaji: "hana",
    commonWriting: "花",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["nature", "plants", "beauty"],
    relatedWords: ["tree", "garden", "spring"]
},
{
    id: "tree_001",
    english: "tree",
    hiragana: "き",
    katakana: "キ",
    kanji: "木",
    romaji: "ki",
    commonWriting: "木",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["nature", "plants", "basic"],
    relatedWords: ["flower", "forest", "leaf"]
},
{
    id: "mountain_001",
    english: "mountain",
    hiragana: "やま",
    katakana: "ヤマ",
    kanji: "山",
    romaji: "yama",
    commonWriting: "山",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["nature", "geography", "places"],
    relatedWords: ["high", "climb", "forest"]
},
{
    id: "sea_001",
    english: "sea/ocean",
    hiragana: "うみ",
    katakana: "ウミ",
    kanji: "海",
    romaji: "umi",
    commonWriting: "海",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["nature", "geography", "water"],
    relatedWords: ["fish", "swim", "blue"]
},
{
    id: "rain_001",
    english: "rain",
    hiragana: "あめ",
    katakana: "アメ",
    kanji: "雨",
    romaji: "ame",
    commonWriting: "雨",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["weather", "nature", "basic"],
    relatedWords: ["water", "cloud", "umbrella"]
},
{
    id: "snow_001",
    english: "snow",
    hiragana: "ゆき",
    katakana: "ユキ",
    kanji: "雪",
    romaji: "yuki",
    commonWriting: "雪",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["weather", "nature", "winter"],
    relatedWords: ["cold", "white", "winter"]
},
{
    id: "wind_001",
    english: "wind",
    hiragana: "かぜ",
    katakana: "カゼ",
    kanji: "風",
    romaji: "kaze",
    commonWriting: "風",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["weather", "nature", "basic"],
    relatedWords: ["air", "blow", "strong"]
},
{
    id: "fire_001",
    english: "fire",
    hiragana: "ひ",
    katakana: "ヒ",
    kanji: "火",
    romaji: "hi",
    commonWriting: "火",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["elements", "basic", "danger"],
    relatedWords: ["hot", "light", "burn"]
},
{
    id: "color_001",
    english: "color",
    hiragana: "いろ",
    katakana: "イロ",
    kanji: "色",
    romaji: "iro",
    commonWriting: "色",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["attributes", "art", "basic"],
    relatedWords: ["red", "blue", "beautiful"]
},
{
    id: "red_001",
    english: "red",
    hiragana: "あかい",
    katakana: "アカイ",
    kanji: "赤い",
    romaji: "akai",
    commonWriting: "赤い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["colors", "adjectives", "basic"],
    relatedWords: ["color", "fire", "blood"]
},
{
    id: "blue_001",
    english: "blue",
    hiragana: "あおい",
    katakana: "アオイ",
    kanji: "青い",
    romaji: "aoi",
    commonWriting: "青い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["colors", "adjectives", "basic"],
    relatedWords: ["color", "sky", "sea"]
},
{
    id: "white_001",
    english: "white",
    hiragana: "しろい",
    katakana: "シロイ",
    kanji: "白い",
    romaji: "shiroi",
    commonWriting: "白い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["colors", "adjectives", "basic"],
    relatedWords: ["color", "snow", "clean"]
},
{
    id: "black_001",
    english: "black",
    hiragana: "くろい",
    katakana: "クロイ",
    kanji: "黒い",
    romaji: "kuroi",
    commonWriting: "黒い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["colors", "adjectives", "basic"],
    relatedWords: ["color", "dark", "night"]
},
{
    id: "new_001",
    english: "new",
    hiragana: "あたらしい",
    katakana: "アタラシイ",
    kanji: "新しい",
    romaji: "atarashii",
    commonWriting: "新しい",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01111",
    tags: ["adjectives", "basic", "time"],
    relatedWords: ["old", "modern", "fresh"]
},
{
    id: "old_001",
    english: "old",
    hiragana: "ふるい",
    katakana: "フルイ",
    kanji: "古い",
    romaji: "furui",
    commonWriting: "古い",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "basic", "time"],
    relatedWords: ["new", "ancient", "past"]
},
{
    id: "fast_001",
    english: "fast",
    hiragana: "はやい",
    katakana: "ハヤイ",
    kanji: "速い",
    romaji: "hayai",
    commonWriting: "速い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "speed", "basic"],
    relatedWords: ["slow", "quick", "run"]
},
{
    id: "slow_001",
    english: "slow",
    hiragana: "おそい",
    katakana: "オソイ",
    kanji: "遅い",
    romaji: "osoi",
    commonWriting: "遅い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "speed", "basic"],
    relatedWords: ["fast", "late", "careful"]
},
{
    id: "strong_001",
    english: "strong",
    hiragana: "つよい",
    katakana: "ツヨイ",
    kanji: "強い",
    romaji: "tsuyoi",
    commonWriting: "強い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "power", "basic"],
    relatedWords: ["weak", "powerful", "muscle"]
},
{
    id: "weak_001",
    english: "weak",
    hiragana: "よわい",
    katakana: "ヨワイ",
    kanji: "弱い",
    romaji: "yowai",
    commonWriting: "弱い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "power", "basic"],
    relatedWords: ["strong", "fragile", "gentle"]
},
{
    id: "high_001",
    english: "high/tall",
    hiragana: "たかい",
    katakana: "タカイ",
    kanji: "高い",
    romaji: "takai",
    commonWriting: "高い",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "height", "basic"],
    relatedWords: ["low", "expensive", "mountain"]
},
{
    id: "low_001",
    english: "low",
    hiragana: "ひくい",
    katakana: "ヒクイ",
    kanji: "低い",
    romaji: "hikui",
    commonWriting: "低い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "height", "basic"],
    relatedWords: ["high", "short", "ground"]
},
{
    id: "long_001",
    english: "long",
    hiragana: "ながい",
    katakana: "ナガイ",
    kanji: "長い",
    romaji: "nagai",
    commonWriting: "長い",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "length", "basic"],
    relatedWords: ["short", "distance", "time"]
},
{
    id: "short_001",
    english: "short",
    hiragana: "みじかい",
    katakana: "ミジカイ",
    kanji: "短い",
    romaji: "mijikai",
    commonWriting: "短い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["adjectives", "length", "basic"],
    relatedWords: ["long", "brief", "small"]
},
{
    id: "heavy_001",
    english: "heavy",
    hiragana: "おもい",
    katakana: "オモイ",
    kanji: "重い",
    romaji: "omoi",
    commonWriting: "重い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "weight", "basic"],
    relatedWords: ["light", "difficult", "burden"]
},
{
    id: "light_001",
    english: "light (weight)",
    hiragana: "かるい",
    katakana: "カルイ",
    kanji: "軽い",
    romaji: "karui",
    commonWriting: "軽い",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "weight", "basic"],
    relatedWords: ["heavy", "easy", "feather"]
},
{
    id: "expensive_001",
    english: "expensive",
    hiragana: "たかい",
    katakana: "タカイ",
    kanji: "高い",
    romaji: "takai",
    commonWriting: "高い",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "price", "shopping"],
    relatedWords: ["cheap", "money", "buy"]
},
{
    id: "cheap_001",
    english: "cheap",
    hiragana: "やすい",
    katakana: "ヤスイ",
    kanji: "安い",
    romaji: "yasui",
    commonWriting: "安い",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["adjectives", "price", "shopping"],
    relatedWords: ["expensive", "money", "buy"]
},
{
    id: "busy_001",
    english: "busy",
    hiragana: "いそがしい",
    katakana: "イソガシイ",
    kanji: "忙しい",
    romaji: "isogashii",
    commonWriting: "忙しい",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01111",
    tags: ["adjectives", "time", "work"],
    relatedWords: ["free", "work", "hurry"]
},
{
    id: "free_001",
    english: "free (time)",
    hiragana: "ひま",
    katakana: "ヒマ",
    kanji: "暇",
    romaji: "hima",
    commonWriting: "暇",
    wordType: "na-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["adjectives", "time", "leisure"],
    relatedWords: ["busy", "time", "relax"]
},
{
    id: "difficult_001",
    english: "difficult",
    hiragana: "むずかしい",
    katakana: "ムズカシイ",
    kanji: "難しい",
    romaji: "muzukashii",
    commonWriting: "難しい",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01111",
    tags: ["adjectives", "challenge", "study"],
    relatedWords: ["easy", "hard", "problem"]
},
{
    id: "easy_001",
    english: "easy",
    hiragana: "やさしい",
    katakana: "ヤサシイ",
    kanji: "易しい",
    romaji: "yasashii",
    commonWriting: "やさしい",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["adjectives", "challenge", "study"],
    relatedWords: ["difficult", "simple", "kind"]
},
{
    id: "interesting_001",
    english: "interesting",
    hiragana: "おもしろい",
    katakana: "オモシロイ",
    kanji: "面白い",
    romaji: "omoshiroi",
    commonWriting: "面白い",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01111",
    tags: ["adjectives", "emotions", "entertainment"],
    relatedWords: ["boring", "fun", "enjoy"]
},
{
    id: "boring_001",
    english: "boring",
    hiragana: "つまらない",
    katakana: "ツマラナイ",
    kanji: "詰まらない",
    romaji: "tsumaranai",
    commonWriting: "つまらない",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01111",
    tags: ["adjectives", "emotions", "entertainment"],
    relatedWords: ["interesting", "dull", "tired"]
},
{
    id: "happy_001",
    english: "happy",
    hiragana: "うれしい",
    katakana: "ウレシイ",
    kanji: "嬉しい",
    romaji: "ureshii",
    commonWriting: "嬉しい",
    wordType: "i-adjective",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["adjectives", "emotions", "feelings"],
    relatedWords: ["sad", "joy", "smile"]
},
{
    id: "sad_001",
    english: "sad",
    hiragana: "かなしい",
    katakana: "カナシイ",
    kanji: "悲しい",
    romaji: "kanashii",
    commonWriting: "悲しい",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["adjectives", "emotions", "feelings"],
    relatedWords: ["happy", "cry", "sorrow"]
},
{
    id: "room_001",
    english: "room",
    hiragana: "へや",
    katakana: "ヘヤ",
    kanji: "部屋",
    romaji: "heya",
    commonWriting: "部屋",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["places", "house", "basic"],
    relatedWords: ["house", "door", "window"]
},
{
    id: "door_001",
    english: "door",
    hiragana: "ドア",
    katakana: "ドア",
    kanji: "",
    romaji: "doa",
    commonWriting: "ドア",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["objects", "house", "basic"],
    relatedWords: ["room", "open", "close"]
},
{
    id: "window_001",
    english: "window",
    hiragana: "まど",
    katakana: "マド",
    kanji: "窓",
    romaji: "mado",
    commonWriting: "窓",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["objects", "house", "basic"],
    relatedWords: ["room", "glass", "view"]
},
{
    id: "chair_001",
    english: "chair",
    hiragana: "いす",
    katakana: "イス",
    kanji: "椅子",
    romaji: "isu",
    commonWriting: "いす",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["objects", "furniture", "basic"],
    relatedWords: ["table", "sit", "room"]
},
{
    id: "table_001",
    english: "table",
    hiragana: "テーブル",
    katakana: "テーブル",
    kanji: "",
    romaji: "teeburu",
    commonWriting: "テーブル",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["objects", "furniture", "basic"],
    relatedWords: ["chair", "eat", "desk"]
},
{
    id: "bed_001",
    english: "bed",
    hiragana: "ベッド",
    katakana: "ベッド",
    kanji: "",
    romaji: "beddo",
    commonWriting: "ベッド",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["objects", "furniture", "sleep"],
    relatedWords: ["sleep", "room", "night"]
},
{
    id: "sleep_001",
    english: "to sleep",
    hiragana: "ねる",
    katakana: "ネル",
    kanji: "寝る",
    romaji: "neru",
    commonWriting: "寝る",
    wordType: "ichidan-verb",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01",
    tags: ["verbs", "daily-life", "basic"],
    relatedWords: ["bed", "night", "tired"]
},
{
    id: "wake_up_001",
    english: "to wake up",
    hiragana: "おきる",
    katakana: "オキル",
    kanji: "起きる",
    romaji: "okiru",
    commonWriting: "起きる",
    wordType: "ichidan-verb",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["verbs", "daily-life", "basic"],
    relatedWords: ["sleep", "morning", "early"]
},
{
    id: "work_001",
    english: "work/job",
    hiragana: "しごと",
    katakana: "シゴト",
    kanji: "仕事",
    romaji: "shigoto",
    commonWriting: "仕事",
    wordType: "noun",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "011",
    tags: ["work", "daily-life", "basic"],
    relatedWords: ["busy", "money", "company"]
},
{
    id: "company_001",
    english: "company",
    hiragana: "かいしゃ",
    katakana: "カイシャ",
    kanji: "会社",
    romaji: "kaisha",
    commonWriting: "会社",
    wordType: "noun",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["work", "business", "places"],
    relatedWords: ["work", "office", "employee"]
},
{
    id: "office_001",
    english: "office",
    hiragana: "オフィス",
    katakana: "オフィス",
    kanji: "",
    romaji: "ofisu",
    commonWriting: "オフィス",
    wordType: "noun",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["work", "places", "business"],
    relatedWords: ["company", "work", "desk"]
},
  {
    id: "how_are_you_001",
    english: "How are you?",
    hiragana: "おげんきですか",
    katakana: "オゲンキデスカ",
    kanji: "お元気ですか",
    romaji: "ogenki desu ka",
    commonWriting: "元気ですか",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01110101",
    tags: ["greetings", "questions", "health"],
    relatedWords: ["good", "fine", "healthy"]
  },
  {
    id: "im_good_001",
    english: "I'm good.",
    hiragana: "げんきです",
    katakana: "ゲンキデス",
    kanji: "元気です",
    romaji: "genki desu",
    commonWriting: "元気です",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "1010",
    tags: ["responses", "health", "feelings"],
    relatedWords: ["fine", "healthy", "well"]
  },
  {
    id: "thank_you_001",
    english: "Thank you.",
    hiragana: "ありがとうございます",
    katakana: "アリガトウゴザイマス",
    kanji: "",
    romaji: "arigatou gozaimasu",
    commonWriting: "ありがとうございます",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01100101",
    tags: ["gratitude", "politeness", "basic"],
    relatedWords: ["thanks", "grateful", "appreciate"]
  },
  {
    id: "im_sorry_001",
    english: "I'm sorry.",
    hiragana: "すみません",
    katakana: "スミマセン",
    kanji: "",
    romaji: "sumimasen",
    commonWriting: "すみません",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["apology", "politeness", "basic"],
    relatedWords: ["excuse", "apologize", "forgive"]
  },
  {
    id: "yes_001",
    english: "Yes.",
    hiragana: "はい",
    katakana: "ハイ",
    kanji: "",
    romaji: "hai",
    commonWriting: "はい",
    wordType: "interjection",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "10",
    tags: ["responses", "agreement", "basic"],
    relatedWords: ["agree", "correct", "okay"]
  },
  {
    id: "no_001",
    english: "No.",
    hiragana: "いいえ",
    katakana: "イイエ",
    kanji: "",
    romaji: "iie",
    commonWriting: "いいえ",
    wordType: "interjection",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "110",
    tags: ["responses", "disagreement", "basic"],
    relatedWords: ["disagree", "wrong", "negative"]
  },
  {
    id: "are_you_ok_001",
    english: "Are you ok?",
    hiragana: "だいじょうぶですか",
    katakana: "ダイジョウブデスカ",
    kanji: "大丈夫ですか",
    romaji: "daijoubu desu ka",
    commonWriting: "大丈夫ですか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011010101",
    tags: ["concern", "questions", "health"],
    relatedWords: ["okay", "fine", "worry"]
  },
  {
    id: "hi_001",
    english: "Hi.",
    hiragana: "こんにちは",
    katakana: "コンニチハ",
    kanji: "",
    romaji: "konnichiwa",
    commonWriting: "こんにちは",
    wordType: "interjection",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01110",
    tags: ["greetings", "basic", "casual"],
    relatedWords: ["hello", "greeting", "meet"]
  },
  {
    id: "sure_001",
    english: "Sure.",
    hiragana: "もちろん",
    katakana: "モチロン",
    kanji: "",
    romaji: "mochiron",
    commonWriting: "もちろん",
    wordType: "adverb",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "0110",
    tags: ["agreement", "responses", "certainty"],
    relatedWords: ["of course", "certainly", "definitely"]
  },
  {
    id: "im_tired_001",
    english: "I'm tired.",
    hiragana: "つかれました",
    katakana: "ツカレマシタ",
    kanji: "疲れました",
    romaji: "tsukaremashita",
    commonWriting: "疲れました",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "011010",
    tags: ["feelings", "physical state", "fatigue"],
    relatedWords: ["exhausted", "weary", "rest"]
  },
  {
    id: "im_sleepy_001",
    english: "I'm sleepy.",
    hiragana: "ねむいです",
    katakana: "ネムイデス",
    kanji: "眠いです",
    romaji: "nemui desu",
    commonWriting: "眠いです",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "1010",
    tags: ["feelings", "physical state", "sleep"],
    relatedWords: ["tired", "drowsy", "sleep"]
  },
  {
    id: "its_hot_001",
    english: "It's hot.",
    hiragana: "あついです",
    katakana: "アツイデス",
    kanji: "暑いです",
    romaji: "atsui desu",
    commonWriting: "暑いです",    
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "1010",
    tags: ["weather", "temperature", "feelings"],
    relatedWords: ["warm", "heat", "summer"]
  },
  {
    id: "its_very_hot_001",
    english: "It's very hot.",
    hiragana: "とてもあついです",
    katakana: "トテモアツイデス",
    kanji: "とても暑いです",
    romaji: "totemo atsui desu",
    commonWriting: "とても暑いです",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011010",
    tags: ["weather", "temperature", "intensity"],
    relatedWords: ["extremely", "very", "hot"]
  },
  {
    id: "its_cold_001",
    english: "It's cold.",
    hiragana: "さむいです",
    katakana: "サムイデス",
    kanji: "寒いです",
    romaji: "samui desu",
    commonWriting: "寒いです",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "1010",
    tags: ["weather", "temperature", "feelings"],
    relatedWords: ["cool", "chilly", "winter"]
  },
  {
    id: "nice_001",
    english: "Nice.",
    hiragana: "いいですね",
    katakana: "イイデスネ",
    kanji: "",
    romaji: "ii desu ne",
    commonWriting: "いいですね",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "10101",
    tags: ["approval", "positive", "reactions"],
    relatedWords: ["good", "great", "wonderful"]
  },
  {
    id: "really_001",
    english: "Really?",
    hiragana: "ほんとうですか",
    katakana: "ホントウデスカ",
    kanji: "本当ですか",
    romaji: "hontou desu ka",
    commonWriting: "本当ですか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "111010",
    tags: ["questions", "surprise", "confirmation"],
    relatedWords: ["true", "seriously", "actually"]
  },
  {
    id: "good_for_you_001",
    english: "Good for you.",
    hiragana: "よかったですね",
    katakana: "ヨカッタデスネ",
    kanji: "良かったですね",
    romaji: "yokatta desu ne",
    commonWriting: "良かったですね",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011010",
    tags: ["congratulations", "happiness", "support"],
    relatedWords: ["congratulations", "happy", "glad"]
  },
  {
    id: "just_a_little_bit_001",
    english: "Just a little bit.",
    hiragana: "ちょっとだけ",
    katakana: "チョットダケ",
    kanji: "",
    romaji: "chotto dake",
    commonWriting: "ちょっとだけ",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "11010",
    tags: ["quantity", "small amount", "moderation"],
    relatedWords: ["little", "small", "bit"]
  },
  {
    id: "dont_worry_001",
    english: "Don't worry.",
    hiragana: "しんぱいしないで",
    katakana: "シンパイシナイデ",
    kanji: "心配しないで",
    romaji: "shinpai shinaide",
    commonWriting: "心配しないで",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N4",
    pronunciation: "111010",
    tags: ["comfort", "reassurance", "advice"],
    relatedWords: ["relax", "calm", "okay"]
  },
  {
    id: "i_understand_001",
    english: "I understand.",
    hiragana: "わかります",
    katakana: "ワカリマス",
    kanji: "分かります",
    romaji: "wakarimasu",
    commonWriting: "分かります",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01010",
    tags: ["comprehension", "agreement", "understanding"],
    relatedWords: ["know", "comprehend", "get"]
  },
  {
    id: "i_dont_understand_001",
    english: "I don't understand.",
    hiragana: "わかりません",
    katakana: "ワカリマセン",
    kanji: "分かりません",
    romaji: "wakarimasen",
    commonWriting: "分かりません",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "010111",
    tags: ["confusion", "learning", "questions"],
    relatedWords: ["confused", "unclear", "help"]
  },
  {
    id: "did_you_understand_001",
    english: "Did you understand?",
    hiragana: "わかりましたか",
    katakana: "ワカリマシタカ",
    kanji: "分かりましたか",
    romaji: "wakarimashita ka",
    commonWriting: "分かりましたか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "010110101",
    tags: ["questions", "comprehension", "checking"],
    relatedWords: ["understand", "clear", "get"]
  },
  {
    id: "wait_001",
    english: "Wait.",
    hiragana: "まって",
    katakana: "マッテ",
    kanji: "待って",
    romaji: "matte",
    commonWriting: "待って",
    wordType: "verb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "11",
    tags: ["requests", "time", "commands"],
    relatedWords: ["hold", "stop", "pause"]
  },
  {
    id: "why_001",
    english: "Why?",
    hiragana: "なぜ",
    katakana: "ナゼ",
    kanji: "",
    romaji: "naze",
    commonWriting: "なぜ",
    wordType: "adverb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "10",
    tags: ["questions", "reason", "curiosity"],
    relatedWords: ["reason", "how come", "what for"]
  },
  {
    id: "me_too_001",
    english: "Me too.",
    hiragana: "わたしも",
    katakana: "ワタシモ",
    kanji: "私も",
    romaji: "watashi mo",
    commonWriting: "私も",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "0110",
    tags: ["agreement", "similarity", "responses"],
    relatedWords: ["also", "same", "likewise"]
  },
  {
    id: "lets_go_001",
    english: "Let's go.",
    hiragana: "いきましょう",
    katakana: "イキマショウ",
    kanji: "行きましょう",
    romaji: "ikimashou",
    commonWriting: "行きましょう",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01111",
    tags: ["movement", "suggestions", "actions"],
    relatedWords: ["move", "leave", "start"]
  },
  {
    id: "lets_go_together_001",
    english: "Let's go together.",
    hiragana: "いっしょにいきましょう",
    katakana: "イッショニイキマショウ",
    kanji: "一緒に行きましょう",
    romaji: "issho ni ikimashou",
    commonWriting: "一緒に行きましょう",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "111001111",
    tags: ["movement", "togetherness", "suggestions"],
    relatedWords: ["together", "with", "accompany"]
  },
  {
    id: "whats_wrong_001",
    english: "What's wrong?",
    hiragana: "どうしましたか",
    katakana: "ドウシマシタカ",
    kanji: "",
    romaji: "doushimashita ka",
    commonWriting: "どうしましたか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111101",
    tags: ["concern", "questions", "problems"],
    relatedWords: ["problem", "matter", "trouble"]
  },
  {
    id: "what_001",
    english: "What?",
    hiragana: "なに",
    katakana: "ナニ",
    kanji: "何",
    romaji: "nani",
    commonWriting: "何",
    wordType: "pronoun",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "10",
    tags: ["questions", "basic", "inquiry"],
    relatedWords: ["which", "huh", "pardon"]
  },
  {
    id: "no_way_001",
    english: "No way.",
    hiragana: "まさか",
    katakana: "マサカ",
    kanji: "",
    romaji: "masaka",
    commonWriting: "まさか",
    wordType: "interjection",
    frequency: 3,
    jlptLevel: "N3",
    pronunciation: "010",
    tags: ["surprise", "disbelief", "shock"],
    relatedWords: ["impossible", "unbelievable", "really"]
  },
  {
    id: "i_cant_believe_it_001",
    english: "I can't believe it.",
    hiragana: "しんじられない",
    katakana: "シンジラレナイ",
    kanji: "信じられない",
    romaji: "shinjirarenai",
    commonWriting: "信じられない",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N3",
    pronunciation: "011110",
    tags: ["surprise", "disbelief", "shock"],
    relatedWords: ["unbelievable", "amazing", "incredible"]
  },
  {
    id: "and_001",
    english: "And?",
    hiragana: "それで",
    katakana: "ソレデ",
    kanji: "",
    romaji: "sore de",
    commonWriting: "それで",
    wordType: "conjunction",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "010",
    tags: ["continuation", "questions", "conversation"],
    relatedWords: ["then", "so", "next"]
  },
  {
    id: "what_do_you_think_001",
    english: "What do you think?",
    hiragana: "どうおもいますか",
    katakana: "ドウオモイマスカ",
    kanji: "どう思いますか",
    romaji: "dou omoimasu ka",
    commonWriting: "どう思いますか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "0011101",
    tags: ["opinions", "questions", "thoughts"],
    relatedWords: ["opinion", "idea", "view"]
  },
  {
    id: "but_001",
    english: "But...",
    hiragana: "でも",
    katakana: "デモ",
    kanji: "",
    romaji: "demo",
    commonWriting: "でも",
    wordType: "conjunction",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "10",
    tags: ["contrast", "however", "basic"],
    relatedWords: ["however", "although", "yet"]
  },
  {
    id: "i_see_001",
    english: "I see.",
    hiragana: "そうですね",
    katakana: "ソウデスネ",
    kanji: "",
    romaji: "sou desu ne",
    commonWriting: "そうですね",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "10101",
    tags: ["understanding", "agreement", "responses"],
    relatedWords: ["understand", "right", "yes"]
  },
  {
    id: "what_was_it_called_001",
    english: "What was it called?",
    hiragana: "なんていいましたか",
    katakana: "ナンテイイマシタカ",
    kanji: "何て言いましたか",
    romaji: "nante iimashita ka",
    commonWriting: "何て言いましたか",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N4",
    pronunciation: "1110110101",
    tags: ["questions", "memory", "names"],
    relatedWords: ["name", "called", "title"]
  },
  {
    id: "i_dont_remember_001",
    english: "I don't remember.",
    hiragana: "おぼえていません",
    katakana: "オボエテイマセン",
    kanji: "覚えていません",
    romaji: "oboete imasen",
    commonWriting: "覚えていません",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "01100111",
    tags: ["memory", "forgetting", "responses"],
    relatedWords: ["forget", "memory", "recall"]
  },
  {
    id: "i_know_that_001",
    english: "I know that.",
    hiragana: "それしっています",
    katakana: "ソレシッテイマス",
    kanji: "それ知っています",
    romaji: "sore shitte imasu",
    commonWriting: "それ知っています",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01111010",
    tags: ["knowledge", "understanding", "responses"],
    relatedWords: ["know", "aware", "familiar"]
  },
  {
    id: "i_didnt_know_that_001",
    english: "I didn't know that.",
    hiragana: "それしりませんでした",
    katakana: "ソレシリマセンデシタ",
    kanji: "それ知りませんでした",
    romaji: "sore shirimasen deshita",
    commonWriting: "それ知りませんでした",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "010111100",
    tags: ["learning", "surprise", "knowledge"],
    relatedWords: ["unaware", "new", "learn"]
  },
  {
    id: "what_did_you_say_001",
    english: "What did you say?",
    hiragana: "なんといいましたか",
    katakana: "ナントイイマシタカ",
    kanji: "何と言いましたか",
    romaji: "nanto iimashita ka",
    commonWriting: "何と言いましたか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "11011101",
    tags: ["questions", "clarification", "listening"],
    relatedWords: ["repeat", "clarify", "understand"]
  },
  {
    id: "can_you_see_it_001",
    english: "Can you see it?",
    hiragana: "みえますか",
    katakana: "ミエマスカ",
    kanji: "見えますか",
    romaji: "miemasu ka",
    commonWriting: "見えますか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "11101",
    tags: ["vision", "questions", "ability"],
    relatedWords: ["see", "look", "visible"]
  },
  {
    id: "just_kidding_001",
    english: "Just kidding.",
    hiragana: "うそです",
    katakana: "ウソデス",
    kanji: "嘘です",
    romaji: "uso desu",
    commonWriting: "嘘です",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N4",
    pronunciation: "010",
    tags: ["humor", "jokes", "playful"],
    relatedWords: ["joke", "lie", "funny"]
  },
  {
    id: "see_you_001",
    english: "See you.",
    hiragana: "またね",
    katakana: "マタネ",
    kanji: "",
    romaji: "mata ne",
    commonWriting: "またね",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "010",
    tags: ["farewell", "casual", "goodbye"],
    relatedWords: ["goodbye", "later", "bye"]
  },
  {
    id: "see_you_tomorrow_001",
    english: "See you tomorrow.",
    hiragana: "またあした",
    katakana: "マタアシタ",
    kanji: "また明日",
    romaji: "mata ashita",
    commonWriting: "また明日",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01110",
    tags: ["farewell", "time", "tomorrow"],
    relatedWords: ["tomorrow", "goodbye", "later"]
  },
  {
    id: "see_you_next_week_001",
    english: "See you next week.",
    hiragana: "またらいしゅう",
    katakana: "マタライシュウ",
    kanji: "また来週",
    romaji: "mata raishuu",
    commonWriting: "また来週",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01110",
    tags: ["farewell", "time", "week"],
    relatedWords: ["week", "goodbye", "later"]
  },
  {
    id: "im_running_a_little_late_001",
    english: "I'm running a little late.",
    hiragana: "ちょっとおくれます",
    katakana: "チョットオクレマス",
    kanji: "ちょっと遅れます",
    romaji: "chotto okuremasu",
    commonWriting: "ちょっと遅れます",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N4",
    pronunciation: "11011010",
    tags: ["time", "lateness", "apology"],
    relatedWords: ["late", "delay", "sorry"]
  },
  {
    id: "im_surprised_001",
    english: "I'm surprised.",
    hiragana: "びっくりしました",
    katakana: "ビックリシマシタ",
    kanji: "",
    romaji: "bikkuri shimashita",
    commonWriting: "びっくりしました",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "11101110",
    tags: ["surprise", "emotions", "reactions"],
    relatedWords: ["shocked", "amazed", "wow"]
  },
  {
    id: "when_001",
    english: "When?",
    hiragana: "いつ",
    katakana: "イツ",
    kanji: "",
    romaji: "itsu",
    commonWriting: "いつ",
    wordType: "adverb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "10",
    tags: ["time", "questions", "basic"],
    relatedWords: ["time", "schedule", "date"]
  },
  {
    id: "where_are_you_now_001",
    english: "Where are you now?",
    hiragana: "いまどこにいますか",
    katakana: "イマドコニイマスカ",
    kanji: "今どこにいますか",
    romaji: "ima doko ni imasu ka",
    commonWriting: "今どこにいますか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "010110101",
    tags: ["location", "questions", "present"],
    relatedWords: ["where", "location", "now"]
  },
  {
    id: "hurry_up_001",
    english: "Hurry up.",
    hiragana: "いそいで",
    katakana: "イソイデ",
    kanji: "急いで",
    romaji: "isoide",
    commonWriting: "急いで",
    wordType: "verb",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "010",
    tags: ["urgency", "commands", "speed"],
    relatedWords: ["quick", "fast", "rush"]
  },
  {
    id: "its_funny_001",
    english: "It's funny.",
    hiragana: "おもしろいです",
    katakana: "オモシロイデス",
    kanji: "面白いです",
    romaji: "omoshiroi desu",
    commonWriting: "面白いです",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01110101",
    tags: ["humor", "entertainment", "positive"],
    relatedWords: ["amusing", "interesting", "fun"]
  },
  {
    id: "its_not_funny_001",
    english: "It's not funny.",
    hiragana: "おもしろくないです",
    katakana: "オモシロクナイデス",
    kanji: "面白くないです",
    romaji: "omoshirokunai desu",
    commonWriting: "面白くないです",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "0111110101",
    tags: ["humor", "disapproval", "negative"],
    relatedWords: ["boring", "serious", "not amusing"]
  },
  {
    id: "im_hungry_001",
    english: "I'm hungry.",
    hiragana: "おなかがすいています",
    katakana: "オナカガスイテイマス",
    kanji: "お腹が空いています",
    romaji: "onaka ga suite imasu",
    commonWriting: "お腹が空いています",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01010110101",
    tags: ["hunger", "physical state", "needs"],
    relatedWords: ["food", "eat", "stomach"]
  },
  {
    id: "im_full_001",
    english: "I'm full.",
    hiragana: "おなかがいっぱいです",
    katakana: "オナカガイッパイデス",
    kanji: "お腹がいっぱいです",
    romaji: "onaka ga ippai desu",
    commonWriting: "お腹がいっぱいです",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "010011110101",
    tags: ["satiety", "physical state", "food"],
    relatedWords: ["satisfied", "enough", "stomach"]
  },
  {
    id: "i_have_a_headache_001",
    english: "I have a headache.",
    hiragana: "あたまがいたいです",
    katakana: "アタマガイタイデス",
    kanji: "頭が痛いです",
    romaji: "atama ga itai desu",
    commonWriting: "頭が痛いです",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "0100110101",
    tags: ["health", "pain", "physical state"],
    relatedWords: ["pain", "sick", "head"]
  },
  {
    id: "what_should_i_do_001",
    english: "What should I do?",
    hiragana: "どうすればいいですか",
    katakana: "ドウスレバイイデスカ",
    kanji: "どうすればいいですか",
    romaji: "dou sureba ii desu ka",
    commonWriting: "どうすればいいですか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "01101110101",
    tags: ["advice", "questions", "help"],
    relatedWords: ["help", "advice", "guidance"]
  },
  {
    id: "i_want_to_see_you_001",
    english: "I want to see you.",
    hiragana: "あいたいです",
    katakana: "アイタイデス",
    kanji: "会いたいです",
    romaji: "aitai desu",
    commonWriting: "会いたいです",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "11010",
    tags: ["emotions", "relationships", "desires"],
    relatedWords: ["meet", "miss", "love"]
  },
  {
    id: "its_cute_001",
    english: "It's cute.",
    hiragana: "かわいいです",
    katakana: "カワイイデス",
    kanji: "可愛いです",
    romaji: "kawaii desu",
    commonWriting: "可愛いです",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "011010",
    tags: ["appearance", "positive", "emotions"],
    relatedWords: ["adorable", "sweet", "lovely"]
  },
  {
    id: "its_not_cute_001",
    english: "It's not cute.",
    hiragana: "かわいくないです",
    katakana: "カワイクナイデス",
    kanji: "可愛くないです",
    romaji: "kawaiku nai desu",
    commonWriting: "可愛くないです",
    wordType: "phrase",
    frequency: 2,
    jlptLevel: "N5",
    pronunciation: "011111010",
    tags: ["appearance", "negative", "criticism"],
    relatedWords: ["ugly", "not pretty", "unattractive"]
  },
  {
    id: "more_001",
    english: "More.",
    hiragana: "もっと",
    katakana: "モット",
    kanji: "",
    romaji: "motto",
    commonWriting: "もっと",
    wordType: "adverb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "11",
    tags: ["quantity", "requests", "increase"],
    relatedWords: ["additional", "extra", "increase"]
  },
  {
    id: "you_are_smart_001",
    english: "You are smart.",
    hiragana: "あたまがいいですね",
    katakana: "アタマガイイデスネ",
    kanji: "頭がいいですね",
    romaji: "atama ga ii desu ne",
    commonWriting: "頭がいいですね",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "01011010101",
    tags: ["compliments", "intelligence", "praise"],
    relatedWords: ["intelligent", "clever", "bright"]
  },
  {
    id: "how_old_are_you_001",
    english: "How old are you?",
    hiragana: "なんさいですか",
    katakana: "ナンサイデスカ",
    kanji: "何歳ですか",
    romaji: "nansai desu ka",
    commonWriting: "何歳ですか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "110101",
    tags: ["age", "questions", "personal"],
    relatedWords: ["age", "years", "old"]
  },
  {
    id: "what_sport_do_you_like_001",
    english: "What sport do you like?",
    hiragana: "どんなスポーツがすきですか",
    katakana: "ドンナスポーツガスキデスカ",
    kanji: "どんなスポーツが好きですか",
    romaji: "donna supoutsu ga suki desu ka",
    commonWriting: "どんなスポーツが好きですか",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "1101111010101",
    tags: ["sports", "preferences", "questions"],
    relatedWords: ["sports", "hobby", "like"]
  },
  {
    id: "whats_your_favorite_anime_001",
    english: "What's your favorite anime?",
    hiragana: "すきなアニメはなんですか",
    katakana: "スキナアニメハナンデスカ",
    kanji: "好きなアニメは何ですか",
    romaji: "suki na anime wa nan desu ka",
    commonWriting: "好きなアニメは何ですか",
    wordType: "phrase",
    frequency: 2,
    jlptLevel: "N5",
    pronunciation: "10101010110101",
    tags: ["anime", "preferences", "questions"],
    relatedWords: ["anime", "favorite", "entertainment"]
  },
  {
    id: "where_are_you_from_001",
    english: "Where are you from?",
    hiragana: "どちらからきましたか",
    katakana: "ドチラカラキマシタカ",
    kanji: "どちらから来ましたか",
    romaji: "dochira kara kimashita ka",
    commonWriting: "どちらから来ましたか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01010111101",
    tags: ["origin", "questions", "personal"],
    relatedWords: ["home", "country", "place"]
  },
  {
    id: "do_you_wanna_come_001",
    english: "Do you wanna come?",
    hiragana: "きませんか",
    katakana: "キマセンカ",
    kanji: "来ませんか",
    romaji: "kimasen ka",
    commonWriting: "来ませんか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["invitations", "questions", "social"],
    relatedWords: ["invite", "join", "come"]
  },
  {
    id: "i_cant_do_it_001",
    english: "I can't do it.",
    hiragana: "できません",
    katakana: "デキマセン",
    kanji: "出来ません",
    romaji: "dekimasen",
    commonWriting: "できません",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["inability", "difficulty", "negative"],
    relatedWords: ["impossible", "difficult", "unable"]
  },
  {
    id: "i_dont_want_to_study_001",
    english: "I don't want to study.",
    hiragana: "べんきょうしたくないです",
    katakana: "ベンキョウシタクナイデス",
    kanji: "勉強したくないです",
    romaji: "benkyou shitakunai desu",
    commonWriting: "勉強したくないです",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "111110111010",
    tags: ["studying", "reluctance", "negative"],
    relatedWords: ["study", "lazy", "don't want"]
  },
  {
    id: "i_dont_wanna_do_anything_001",
    english: "I don't wanna do anything.",
    hiragana: "なにもしたくないです",
    katakana: "ナニモシタクナイデス",
    kanji: "何もしたくないです",
    romaji: "nanimo shitakunai desu",
    commonWriting: "何もしたくないです",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N4",
    pronunciation: "1010111010",
    tags: ["apathy", "tiredness", "negative"],
    relatedWords: ["lazy", "tired", "unmotivated"]
  },
  {
    id: "look_001",
    english: "Look.",
    hiragana: "みて",
    katakana: "ミテ",
    kanji: "見て",
    romaji: "mite",
    commonWriting: "見て",
    wordType: "verb",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "10",
    tags: ["attention", "commands", "vision"],
    relatedWords: ["see", "watch", "observe"]
  },
  {
    id: "can_you_hear_that_001",
    english: "Can you hear that?",
    hiragana: "きこえますか",
    katakana: "キコエマスカ",
    kanji: "聞こえますか",
    romaji: "kikoemasu ka",
    commonWriting: "聞こえますか",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "011101",
    tags: ["hearing", "questions", "senses"],
    relatedWords: ["hear", "sound", "listen"]
  },
  {
    id: "whatever_is_fine_001",
    english: "Whatever is fine.",
    hiragana: "なんでもいいです",
    katakana: "ナンデモイイデス",
    kanji: "何でもいいです",
    romaji: "nandemo ii desu",
    commonWriting: "何でもいいです",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "110110101",
    tags: ["flexibility", "agreement", "casual"],
    relatedWords: ["anything", "okay", "fine"]
  },
  {
    id: "its_been_a_while_001",
    english: "It's been a while.",
    hiragana: "ひさしぶりですね",
    katakana: "ヒサシブリデスネ",
    kanji: "久しぶりですね",
    romaji: "hisashiburi desu ne",
    commonWriting: "久しぶりですね",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "0111010101",
    tags: ["time", "reunion", "greetings"],
    relatedWords: ["long time", "reunion", "again"]
  },
  {
    id: "how_have_you_been_001",
    english: "How have you been?",
    hiragana: "げんきでしたか",
    katakana: "ゲンキデシタカ",
    kanji: "元気でしたか",
    romaji: "genki deshita ka",
    commonWriting: "元気でしたか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "10110101",
    tags: ["greetings", "health", "questions"],
    relatedWords: ["health", "well", "doing"]
  },
  {
    id: "im_nervous_001",
    english: "I'm nervous.",
    hiragana: "きんちょうしています",
    katakana: "キンチョウシテイマス",
    kanji: "緊張しています",
    romaji: "kinchou shite imasu",
    commonWriting: "緊張しています",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N3",
    pronunciation: "111011010",
    tags: ["emotions", "anxiety", "feelings"],
    relatedWords: ["anxious", "worried", "tense"]
  },
  {
    id: "good_luck_001",
    english: "Good luck.",
    hiragana: "がんばって",
    katakana: "ガンバッテ",
    kanji: "頑張って",
    romaji: "ganbatte",
    commonWriting: "頑張って",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "0111",
    tags: ["encouragement", "support", "motivation"],
    relatedWords: ["try hard", "do your best", "fight"]
  },
  {
    id: "dont_cry_001",
    english: "Don't cry.",
    hiragana: "なかないで",
    katakana: "ナカナイデ",
    kanji: "泣かないで",
    romaji: "nakanaide",
    commonWriting: "泣かないで",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N4",
    pronunciation: "01110",
    tags: ["comfort", "emotions", "sadness"],
    relatedWords: ["comfort", "sad", "tears"]
  },
  {
    id: "it_cant_be_helped_001",
    english: "It can't be helped.",
    hiragana: "しかたがないです",
    katakana: "シカタガナイデス",
    kanji: "仕方がないです",
    romaji: "shikata ga nai desu",
    commonWriting: "仕方がないです",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N3",
    pronunciation: "010110101",
    tags: ["acceptance", "resignation", "philosophy"],
    relatedWords: ["unavoidable", "accept", "nothing to do"]
  },
  {
    id: "i_like_it_001",
    english: "I like it.",
    hiragana: "すきです",
    katakana: "スキデス",
    kanji: "好きです",
    romaji: "suki desu",
    commonWriting: "好きです",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "1010",
    tags: ["preferences", "positive", "emotions"],
    relatedWords: ["love", "enjoy", "prefer"]
  },
  {
    id: "i_dont_like_it_001",
    english: "I don't like it.",
    hiragana: "すきじゃないです",
    katakana: "スキジャナイデス",
    kanji: "好きじゃないです",
    romaji: "suki ja nai desu",
    commonWriting: "好きじゃないです",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "10111010",
    tags: ["preferences", "negative", "dislike"],
    relatedWords: ["dislike", "hate", "not enjoy"]
  },
  {
    id: "im_busy_001",
    english: "I'm busy.",
    hiragana: "いそがしいです",
    katakana: "イソガシイデス",
    kanji: "忙しいです",
    romaji: "isogashii desu",
    commonWriting: "忙しいです",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "01110101",
    tags: ["time", "work", "unavailable"],
    relatedWords: ["occupied", "working", "no time"]
  },
  {
    id: "are_you_busy_001",
    english: "Are you busy?",
    hiragana: "いそがしいですか",
    katakana: "イソガシイデスカ",
    kanji: "忙しいですか",
    romaji: "isogashii desu ka",
    commonWriting: "忙しいですか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0111010101",
    tags: ["time", "questions", "availability"],
    relatedWords: ["free", "available", "time"]
  },
  {
    id: "see_you_next_time_001",
    english: "See you next time.",
    hiragana: "またこんど",
    katakana: "マタコンド",
    kanji: "また今度",
    romaji: "mata kondo",
    commonWriting: "また今度",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "0110",
    tags: ["farewell", "future", "goodbye"],
    relatedWords: ["later", "next time", "goodbye"]
  },
  {
    id: "ill_text_you_001",
    english: "I'll text you.",
    hiragana: "メールします",
    katakana: "メールシマス",
    kanji: "",
    romaji: "meeru shimasu",
    commonWriting: "メールします",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "110110",
    tags: ["communication", "technology", "contact"],
    relatedWords: ["message", "contact", "phone"]
  },
  {
    id: "call_me_001",
    english: "Call me.",
    hiragana: "でんわして",
    katakana: "デンワシテ",
    kanji: "電話して",
    romaji: "denwa shite",
    commonWriting: "電話して",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "11010",
    tags: ["communication", "requests", "phone"],
    relatedWords: ["phone", "contact", "talk"]
  },
  {
    id: "im_looking_forward_to_it_001",
    english: "I'm looking forward to it.",
    hiragana: "たのしみです",
    katakana: "タノシミデス",
    kanji: "楽しみです",
    romaji: "tanoshimi desu",
    commonWriting: "楽しみです",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "01110101",
    tags: ["anticipation", "excitement", "future"],
    relatedWords: ["excited", "anticipate", "wait"]
  },
  {
    id: "its_easy_to_understand_001",
    english: "It's easy to understand.",
    hiragana: "わかりやすいです",
    katakana: "ワカリヤスイデス",
    kanji: "分かりやすいです",
    romaji: "wakariyasui desu",
    commonWriting: "分かりやすいです",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N4",
    pronunciation: "010111010",
    tags: ["comprehension", "clarity", "learning"],
    relatedWords: ["clear", "simple", "obvious"]
  },
  {
    id: "its_difficult_to_understand_001",
    english: "It's difficult to understand.",
    hiragana: "わかりにくいです",
    katakana: "ワカリニクイデス",
    kanji: "分かりにくいです",
    romaji: "wakarinikui desu",
    commonWriting: "分かりにくいです",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N4",
    pronunciation: "010111010",
    tags: ["comprehension", "difficulty", "confusion"],
    relatedWords: ["confusing", "complex", "hard"]
  },
  {
    id: "can_you_open_the_window_001",
    english: "Can you open the window?",
    hiragana: "まどをあけてください",
    katakana: "マドヲアケテクダサイ",
    kanji: "窓を開けてください",
    romaji: "mado wo akete kudasai",
    commonWriting: "窓を開けてください",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N5",
    pronunciation: "1001110101",
    tags: ["requests", "actions", "polite"],
    relatedWords: ["window", "open", "please"]
  },
  {
    id: "congratulations_001",
    english: "Congratulations.",
    hiragana: "おめでとうございます",
    katakana: "オメデトウゴザイマス",
    kanji: "",
    romaji: "omedetou gozaimasu",
    commonWriting: "おめでとうございます",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01100101",
    tags: ["celebration", "congratulations", "formal"],
    relatedWords: ["celebrate", "achievement", "success"]
  },
  {
    id: "can_you_say_that_again_001",
    english: "Can you say that again?",
    hiragana: "もういちどいってください",
    katakana: "モウイチドイッテクダサイ",
    kanji: "もう一度言ってください",
    romaji: "mou ichido itte kudasai",
    commonWriting: "もう一度言ってください",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "10110110101",
    tags: ["requests", "repetition", "listening"],
    relatedWords: ["repeat", "again", "please"]
  },
  {
    id: "i_forgot_001",
    english: "I forgot.",
    hiragana: "わすれました",
    katakana: "ワスレマシタ",
    kanji: "忘れました",
    romaji: "wasuremashita",
    commonWriting: "忘れました",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "01110",
    tags: ["memory", "forgetting", "mistakes"],
    relatedWords: ["forget", "memory", "oops"]
  },
  {
    id: "wonderful_001",
    english: "Wonderful.",
    hiragana: "すばらしい",
    katakana: "スバラシイ",
    kanji: "素晴らしい",
    romaji: "subarashii",
    commonWriting: "素晴らしい",
    wordType: "i-adjective",
    frequency: 3,
    jlptLevel: "N3",
    pronunciation: "01110",
    tags: ["praise", "positive", "admiration"],
    relatedWords: ["amazing", "great", "excellent"]
  },
  {
    id: "what_time_is_it_001",
    english: "What time is it?",
    hiragana: "いまなんじですか",
    katakana: "イマナンジデスカ",
    kanji: "今何時ですか",
    romaji: "ima nanji desu ka",
    commonWriting: "今何時ですか",
    wordType: "phrase",
    frequency: 5,
    jlptLevel: "N5",
    pronunciation: "0110101",
    tags: ["time", "questions", "basic"],
    relatedWords: ["time", "clock", "hour"]
  },
  {
    id: "what_do_you_want_to_eat_001",
    english: "What do you want to eat?",
    hiragana: "なにをたべたいですか",
    katakana: "ナニヲタベタイデスカ",
    kanji: "何を食べたいですか",
    romaji: "nani wo tabetai desu ka",
    commonWriting: "何を食べたいですか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "10011010101",
    tags: ["food", "questions", "desires"],
    relatedWords: ["eat", "food", "hungry"]
  },
  {
    id: "what_do_you_want_to_drink_001",
    english: "What do you want to drink?",
    hiragana: "なにをのみたいですか",
    katakana: "ナニヲノミタイデスカ",
    kanji: "何を飲みたいですか",
    romaji: "nani wo nomitai desu ka",
    commonWriting: "何を飲みたいですか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "1001010101",
    tags: ["drinks", "questions", "desires"],
    relatedWords: ["drink", "beverage", "thirsty"]
  },
  {
    id: "im_not_sure_yet_001",
    english: "I'm not sure yet.",
    hiragana: "まだわかりません",
    katakana: "マダワカリマセン",
    kanji: "まだ分かりません",
    romaji: "mada wakarimasen",
    commonWriting: "まだ分かりません",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "10010111",
    tags: ["uncertainty", "time", "decisions"],
    relatedWords: ["unsure", "maybe", "thinking"]
  },
  {
    id: "im_almost_there_001",
    english: "I'm almost there.",
    hiragana: "もうすぐつきます",
    katakana: "モウスグツキマス",
    kanji: "もうすぐ着きます",
    romaji: "mou sugu tsukimasu",
    commonWriting: "もうすぐ着きます",
    wordType: "phrase",
    frequency: 3,
    jlptLevel: "N4",
    pronunciation: "1011010",
    tags: ["location", "time", "arrival"],
    relatedWords: ["arrive", "soon", "close"]
  },
  {
    id: "i_think_so_too_001",
    english: "I think so, too.",
    hiragana: "わたしもそうおもいます",
    katakana: "ワタシモソウオモイマス",
    kanji: "私もそう思います",
    romaji: "watashi mo sou omoimasu",
    commonWriting: "私もそう思います",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N4",
    pronunciation: "011010011",
    tags: ["agreement", "opinions", "thoughts"],
    relatedWords: ["agree", "same", "opinion"]
  },
  {
    id: "who_is_it_001",
    english: "Who is it?",
    hiragana: "だれですか",
    katakana: "ダレデスカ",
    kanji: "誰ですか",
    romaji: "dare desu ka",
    commonWriting: "誰ですか",
    wordType: "phrase",
    frequency: 4,
    jlptLevel: "N5",
    pronunciation: "10101",
    tags: ["questions", "identity", "people"],
    relatedWords: ["who", "person", "name"]
    }
];

// Conjugation functions
function conjugateGodanVerb(verb) {
    const stem = verb.slice(0, -1);
    const ending = verb.slice(-1);
    
    const conjugationMap = {
        'う': { a: 'わ', i: 'い', u: 'う', e: 'え', o: 'お', te: 'っ' },
        'く': { a: 'か', i: 'き', u: 'く', e: 'け', o: 'こ', te: 'い' },
        'ぐ': { a: 'が', i: 'ぎ', u: 'ぐ', e: 'げ', o: 'ご', te: 'い' },
        'す': { a: 'さ', i: 'し', u: 'す', e: 'せ', o: 'そ', te: 'し' },
        'つ': { a: 'た', i: 'ち', u: 'つ', e: 'て', o: 'と', te: 'っ' },
        'ぬ': { a: 'な', i: 'に', u: 'ぬ', e: 'ね', o: 'の', te: 'ん' },
        'ぶ': { a: 'ば', i: 'び', u: 'ぶ', e: 'べ', o: 'ぼ', te: 'ん' },
        'む': { a: 'ま', i: 'み', u: 'む', e: 'め', o: 'も', te: 'ん' },
        'る': { a: 'ら', i: 'り', u: 'る', e: 'れ', o: 'ろ', te: 'っ' }
    };

    const forms = conjugationMap[ending];
    if (!forms) return null;

    return {
        dictionary: verb,
        polite: {
        present: stem + forms.i + 'ます',
        past: stem + forms.i + 'ました',
        negative: stem + forms.i + 'ません',
        pastNegative: stem + forms.i + 'ませんでした'
        },
        casual: {
        present: verb,
        past: stem + forms.te + 'た',
        negative: stem + forms.a + 'ない',
        pastNegative: stem + forms.a + 'なかった'
        },
        teForm: stem + forms.te + 'て',
        potential: stem + forms.e + 'る',
        passive: stem + forms.a + 'れる',
        causative: stem + forms.a + 'せる',
        imperative: stem + forms.e,
        volitional: stem + forms.o + 'う'
    };
}

function conjugateIAdjective(adjective) {
    const stem = adjective.slice(0, -1);
    return {
        present: adjective,
        past: stem + 'かった',
        negative: stem + 'くない',
        pastNegative: stem + 'くなかった',
        adverb: stem + 'く',
        teForm: stem + 'くて',
        conditional: stem + 'ければ',
        polite: {
        present: adjective + 'です',
        past: stem + 'かったです',
        negative: stem + 'くないです',
        pastNegative: stem + 'くなかったです'
        }
    };
}

function conjugateNaAdjective(adjective) {
    return {
        present: adjective,
        presentBe: adjective + 'だ',
        past: adjective + 'だった',
        negative: adjective + 'じゃない',
        pastNegative: adjective + 'じゃなかった',
        adverb: adjective + 'に',
        teForm: adjective + 'で',
        conditional: adjective + 'なら',
        polite: {
        present: adjective + 'です',
        past: adjective + 'でした',
        negative: adjective + 'じゃないです',
        pastNegative: adjective + 'じゃなかったです'
        }
    };
}

function getConjugations(word) {
    if (!word || !word.commonWriting || !word.wordType) {
        return null;
    }
    
    switch(word.wordType) {
        case 'godan-verb':
        return conjugateGodanVerb(word.commonWriting);
        case 'i-adjective':
        return conjugateIAdjective(word.commonWriting);
        case 'na-adjective':
        return conjugateNaAdjective(word.commonWriting);
        default:
        return null;
    }
}

// Conjugation Tool Component
function ConjugationTool({ words }) {
    const [selectedWord, setSelectedWord] = useState('');
    const [conjugations, setConjugations] = useState(null);

    const handleWordChange = (wordId) => {
        const word = words.find(w => w.id === wordId);
        setSelectedWord(wordId);
        setConjugations(getConjugations(word));
    };

    const conjugatableWords = words.filter(word => 
        ['godan-verb', 'ichidan-verb', 'i-adjective', 'na-adjective'].includes(word.wordType)
    );

    return (
        <div className="bg-gray-800 rounded-lg shadow-sm p-6 max-w-4xl mx-auto">
        <h2 className="text-xl font-bold mb-6 text-white">Conjugation Tool</h2>
        
        <div className="space-y-6">
            <div>
            <label className="block text-sm font-medium mb-2 text-gray-200">Select Word</label>
            <select
                value={selectedWord}
                onChange={(e) => handleWordChange(e.target.value)}
                className="w-full p-2 border border-gray-600 rounded-md bg-gray-700 text-white"
            >
                <option value="">Choose a word...</option>
                {conjugatableWords.map(word => (
                <option key={word.id} value={word.id}>
                    {word.commonWriting} ({word.english}) - {word.wordType}
                </option>
                ))}
            </select>
            </div>

            {conjugations && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {conjugations.polite && (
                <div>
                    <h3 className="font-semibold mb-3 text-white">Polite Forms</h3>
                    <div className="space-y-2 text-sm text-gray-300">
                    <div><strong className="text-gray-200">Present:</strong> {conjugations.polite.present}</div>
                    <div><strong className="text-gray-200">Past:</strong> {conjugations.polite.past}</div>
                    <div><strong className="text-gray-200">Negative:</strong> {conjugations.polite.negative}</div>
                    <div><strong className="text-gray-200">Past Negative:</strong> {conjugations.polite.pastNegative}</div>
                    </div>
                </div>
                )}

                {conjugations.casual && (
                <div>
                    <h3 className="font-semibold mb-3 text-white">Casual Forms</h3>
                    <div className="space-y-2 text-sm text-gray-300">
                    <div><strong className="text-gray-200">Present:</strong> {conjugations.casual.present}</div>
                    <div><strong className="text-gray-200">Past:</strong> {conjugations.casual.past}</div>
                    <div><strong className="text-gray-200">Negative:</strong> {conjugations.casual.negative}</div>
                    <div><strong className="text-gray-200">Past Negative:</strong> {conjugations.casual.pastNegative}</div>
                    </div>
                </div>
                )}

                {(conjugations.teForm || conjugations.potential) && (
                <div>
                    <h3 className="font-semibold mb-3 text-white">Other Forms</h3>
                    <div className="space-y-2 text-sm text-gray-300">
                    {conjugations.teForm && <div><strong className="text-gray-200">Te-form:</strong> {conjugations.teForm}</div>}
                    {conjugations.potential && <div><strong className="text-gray-200">Potential:</strong> {conjugations.potential}</div>}
                    {conjugations.passive && <div><strong className="text-gray-200">Passive:</strong> {conjugations.passive}</div>}
                    {conjugations.causative && <div><strong className="text-gray-200">Causative:</strong> {conjugations.causative}</div>}
                    {conjugations.adverb && <div><strong className="text-gray-200">Adverb:</strong> {conjugations.adverb}</div>}
                    </div>
                </div>
                )}
            </div>
            )}
        </div>
        </div>
    );
}
